version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    ports:
      - "4321:4321"
    stdin_open: true
    tty: true
